"""Integration tests against the platform's real LangGraph checkpointer.

W3 D1 deliverable. Our handlers (``run.py`` / ``review.py`` / ``scheduled.py``)
all use ``ctx.store.langgraph_checkpointer`` — at deploy time this is the
platform-provided ``_LangGraphCheckpointerAdapter`` from
``.edgeone/agent-python/_platform/memory.py``. Locally and in CI we use
``InMemorySaver`` for the rest of the test suite (faster, no I/O).

This test file bridges that gap: it imports the platform's adapter from a
sibling template's ``.edgeone/agent-python`` directory and runs the same
pause+resume scenarios against it. If the platform code is not reachable
(e.g. running on a fresh checkout where ``pnpm dev`` hasn't generated the
``.edgeone/`` tree yet), the entire module is skipped with a clear reason.

How the platform adapter is exercised:

  - ``ConversationMemory(blob_store, run_id)`` is instantiated against a
    ``LocalFileBlobStore`` rooted at ``tmp_path`` (one Path per test → full
    isolation; no cross-test leakage).
  - ``memory.langgraph_checkpointer`` returns the lazy-singleton adapter,
    which inherits from ``langgraph.checkpoint.base.BaseCheckpointSaver``.
  - We compile our review-only graph with this checkpointer, simulate an
    interrupt+resume sequence, and assert the state survives.

Run with::

    pytest agents/email/tests/test_platform_checkpointer.py -v
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

import pytest


# ─── Load platform code (skip module if unavailable) ────────────────────────


def _platform_paths() -> list[Path]:
    """Possible locations of the platform ``_platform`` package."""
    here = Path(__file__).resolve()
    candidates = [
        # Local: this template's own .edgeone/agent-python/ (when generated by pnpm dev)
        here.parents[3] / ".edgeone" / "agent-python",
        # Sibling: marketing template's .edgeone/agent-python/ (most likely on dev machines)
        here.parents[4] / "marketing-campaign-planner-crewai" / ".edgeone" / "agent-python",
        # Fallback: ai-trends-scheduled-summary
        here.parents[4] / "ai-trends-scheduled-summary" / ".edgeone" / "agent-python",
    ]
    return [p for p in candidates if (p / "_platform" / "memory.py").exists()]


_PLATFORM_DIR: Path | None = next(iter(_platform_paths()), None)
if _PLATFORM_DIR is None:
    pytest.skip(
        "Platform _platform package not found. This integration test needs "
        "either this template's .edgeone/agent-python/ (run `pnpm dev` once) "
        "or a sibling template's .edgeone/agent-python/ to be present. "
        "Skipping cross-platform-checkpointer tests.",
        allow_module_level=True,
    )

if str(_PLATFORM_DIR) not in sys.path:
    sys.path.insert(0, str(_PLATFORM_DIR))

# Import everything we need; skip the module gracefully if any piece is missing
# (e.g. platform code's optional langgraph dependency wasn't pre-installed).
try:
    from _platform.local_blob_store import LocalFileBlobStore  # noqa: E402
    from _platform.memory import ConversationMemory  # noqa: E402
    from langgraph.checkpoint.base import BaseCheckpointSaver  # noqa: E402
    from langgraph.graph import END, START, StateGraph  # noqa: E402
    from langgraph.types import Command  # noqa: E402
except ImportError as _import_exc:
    pytest.skip(
        f"Platform integration imports failed: {_import_exc}. "
        f"Install requirements.txt and ensure {_PLATFORM_DIR}/_platform exists.",
        allow_module_level=True,
    )

from _models import DraftItem  # noqa: E402
from _nodes import review  # noqa: E402
from _state import EmailAssistantState  # noqa: E402


# ─── Helpers ────────────────────────────────────────────────────────────────


def _make_memory(tmp_path: Path, *, run_id: str = "test-run") -> ConversationMemory:
    """Construct a ConversationMemory backed by the local file blob store."""
    blob = LocalFileBlobStore("test-store", tmp_path)
    return ConversationMemory(blob, run_id)


def _draft(email_id: str = "m1", body: str = "draft body") -> DraftItem:
    return DraftItem(
        email_id=email_id,
        to=["alice@x.com"],
        subject="Re: Hi",
        body=body,
        tone="friendly_professional",
        confidence=0.8,
        rationale="",
    )


def _build_review_only_graph(checkpointer):
    g = StateGraph(EmailAssistantState)
    g.add_node("review", review)
    g.add_edge(START, "review")
    g.add_edge("review", END)
    return g.compile(checkpointer=checkpointer)


# ─── Adapter contract ───────────────────────────────────────────────────────


def test_platform_checkpointer_is_a_base_checkpoint_saver(tmp_path):
    """The platform adapter must be an instance of LangGraph's
    BaseCheckpointSaver — that's what StateGraph.compile expects."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer
    assert isinstance(saver, BaseCheckpointSaver), (
        f"Platform checkpointer should subclass BaseCheckpointSaver, "
        f"got {type(saver).__mro__}"
    )


def test_platform_checkpointer_is_lazy_singleton(tmp_path):
    """Repeated reads of ``langgraph_checkpointer`` must return the same
    instance — otherwise our run.py and review.py building separate graphs
    on different requests would each get a fresh saver and lose state."""
    memory = _make_memory(tmp_path)
    a = memory.langgraph_checkpointer
    b = memory.langgraph_checkpointer
    assert a is b


def test_platform_checkpointer_exposes_async_api(tmp_path):
    """All four async methods our handlers / LangGraph internals call must
    exist on the adapter."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer
    for name in ("aget_tuple", "aput", "aput_writes", "alist"):
        assert hasattr(saver, name), f"adapter missing {name}"


# ─── Pause + resume against the platform adapter ────────────────────────────


def test_review_pauses_and_persists_to_platform_checkpointer(tmp_path):
    """The same scenario as test_hitl_resume.test_review_pauses_at_interrupt_*
    but against the platform's real adapter, NOT InMemorySaver."""
    memory = _make_memory(tmp_path)
    app = _build_review_only_graph(memory.langgraph_checkpointer)
    config = {"configurable": {"thread_id": "t-platform-pause"}}

    async def _run():
        events = []
        async for event in app.astream(
            {"pending_review": _draft("m1"), "auto_approve": False},
            config=config,
            stream_mode="updates",
        ):
            events.append(event)
        return events

    events = asyncio.run(_run())
    interrupts = [e for e in events if "__interrupt__" in e]
    assert interrupts, f"expected __interrupt__, got: {events}"


def test_cross_session_resume_with_platform_checkpointer(tmp_path):
    """The most important integration scenario: two separate ``build_graph``
    calls (mirroring run.py + review.py living in different SCF instances)
    share the same persistent checkpointer and the second one resumes the
    paused state from the first."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer
    config = {"configurable": {"thread_id": "t-platform-cross"}}

    async def _go():
        # SCF instance 1: starts the graph, hits interrupt, exits
        app1 = _build_review_only_graph(saver)
        async for _ in app1.astream(
            {"pending_review": _draft("m42"), "auto_approve": False},
            config=config,
            stream_mode="updates",
        ):
            pass
        # SCF instance 2: completely fresh app object, same persistent saver
        app2 = _build_review_only_graph(saver)
        async for _ in app2.astream(
            Command(resume={"action": "approve"}),
            config=config,
            stream_mode="updates",
        ):
            pass
        snap = await app2.aget_state(config)
        return snap.values

    values = asyncio.run(_go())
    decisions = values.get("review_decisions") or []
    assert len(decisions) == 1
    assert decisions[0].email_id == "m42"
    assert decisions[0].action == "approve"


def test_cross_session_resume_with_edited_body(tmp_path):
    """Resume with a non-trivial payload (``edited_body``) — verifies the
    adapter's pickle path round-trips arbitrary string content correctly."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer
    config = {"configurable": {"thread_id": "t-platform-edit"}}
    custom_body = "我重写了这封邮件 — multibyte字符 + emoji 🚀"

    async def _go():
        app1 = _build_review_only_graph(saver)
        async for _ in app1.astream(
            {"pending_review": _draft("m99"), "auto_approve": False},
            config=config,
            stream_mode="updates",
        ):
            pass
        app2 = _build_review_only_graph(saver)
        async for _ in app2.astream(
            Command(resume={"action": "edit", "edited_body": custom_body}),
            config=config,
            stream_mode="updates",
        ):
            pass
        snap = await app2.aget_state(config)
        return snap.values

    values = asyncio.run(_go())
    decisions = values.get("review_decisions") or []
    assert decisions[0].action == "edit"
    assert decisions[0].edited_body == custom_body


def test_separate_thread_ids_isolate_checkpoints(tmp_path):
    """Two different conversation_ids must produce independent checkpoints
    — critical for the cron path which uses ``scheduled:{date}:{run_id}`` and
    must NEVER interfere with a parallel user conversation."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer

    async def _go():
        app = _build_review_only_graph(saver)
        # Thread A pauses
        cfg_a = {"configurable": {"thread_id": "t-iso-A"}}
        async for _ in app.astream(
            {"pending_review": _draft("a1"), "auto_approve": False},
            config=cfg_a,
            stream_mode="updates",
        ):
            pass
        # Thread B independently auto-approves
        cfg_b = {"configurable": {"thread_id": "t-iso-B"}}
        async for _ in app.astream(
            {"pending_review": _draft("b1"), "auto_approve": True},
            config=cfg_b,
            stream_mode="updates",
        ):
            pass
        # Now resume A — should see ONLY a1, not b1
        async for _ in app.astream(
            Command(resume={"action": "approve"}),
            config=cfg_a,
            stream_mode="updates",
        ):
            pass
        snap_a = await app.aget_state(cfg_a)
        snap_b = await app.aget_state(cfg_b)
        return snap_a.values, snap_b.values

    values_a, values_b = asyncio.run(_go())
    assert [d.email_id for d in (values_a.get("review_decisions") or [])] == ["a1"]
    assert [d.email_id for d in (values_b.get("review_decisions") or [])] == ["b1"]


# ─── Direct adapter API smoke tests (no graph) ──────────────────────────────


def test_aget_tuple_returns_none_for_unknown_thread(tmp_path):
    """The adapter must return ``None`` (not raise) for a thread_id that
    has never been written to. LangGraph relies on this for fresh threads."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer

    async def _go():
        return await saver.aget_tuple({"configurable": {"thread_id": "never-existed"}})

    result = asyncio.run(_go())
    assert result is None


def test_alist_returns_empty_for_unknown_thread(tmp_path):
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer

    async def _go():
        return await saver.alist({"configurable": {"thread_id": "ghost"}})

    result = asyncio.run(_go())
    assert result == []


def test_aput_then_aget_round_trips_minimal_checkpoint(tmp_path):
    """Direct aput → aget_tuple round trip with a minimal valid checkpoint
    payload. Verifies the JSON+pickle serialization end-to-end."""
    memory = _make_memory(tmp_path)
    saver = memory.langgraph_checkpointer
    config = {"configurable": {"thread_id": "t-direct-roundtrip"}}
    checkpoint = {
        "id": "ckpt-1",
        "ts": "2026-05-20T00:00:00Z",
        "v": 1,
        "channel_values": {"foo": "bar"},
        "channel_versions": {"foo": 1},
        "versions_seen": {},
    }

    async def _go():
        await saver.aput(config, checkpoint, metadata={"source": "test"})
        result = await saver.aget_tuple(config)
        return result

    tup = asyncio.run(_go())
    assert tup is not None
    assert tup.checkpoint["id"] == "ckpt-1"
    assert tup.checkpoint["channel_values"] == {"foo": "bar"}
